version: '2.4'

services:

  idilic:
    volumes: ["../../:/app", "/tmp:/tmp"]
    extends:
      file: base.yml
      service: idilic

  server:
    ports: ['${IDS_EXPOSE_HTTP}:8080']
    volumes: ["../../:/app", "/tmp:/tmp"]
    extends:
      file: base.yml
      service: server
